server:
  port: 8888

spring:
  main:
    web-application-type: reactive

  application:
    name: api-gateway

  boot:
    admin:
      context-path: /dashboard

  cloud:
    gateway:
      server:
        webflux:
          routes:
            # PU1: Product Processing Unit
            - id: product-service
              uri: lb://PRODUCT-SERVICE
              predicates:
                - Path=/api/products/**

            # PU2: Cart Processing Unit
            - id: cart-service
              uri: lb://CART-SERVICE
              predicates:
                - Path=/api/cart/**

            # PU3: Order Processing Unit
            - id: order-service
              uri: lb://ORDER-SERVICE
              predicates:
                - Path=/api/checkout/**, /api/orders/**

            # PU4: Inventory Processing Unit
            - id: inventory-service
              uri: lb://INVENTORY-SERVICE
              predicates:
                - Path=/api/stock/**

          # --- CẤU HÌNH CORS CHO FRONTEND ---
          global-cors:
            cors-configurations:
                '[/**]':
                    allowedOriginPatterns: "*"
                    allowedMethods:
                    - GET
                    - POST
                    - PUT
                    - DELETE
                    - OPTIONS
                    allowedHeaders: "*"
                    allowCredentials: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://192.168.1.82:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*" # Mở tất cả các cổng giám sát (health, info, metrics, gateway...)
  endpoint:
    health:
      show-details: always