services:
  # 1. DỊCH VỤ DATABASE (Chạy ngầm)
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    ports:
      - "3306:3306"

  # 2. DỊCH VỤ GIAO DIỆN QUẢN LÝ (Giao tiếp với người dùng)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_gui
    environment:
      PMA_HOST: db 
      PMA_PORT: 3306
    ports:
      - "8081:80"
    depends_on:
      - db