server:
  port: 8082

spring:
  application:
    name: movie-service
  datasource:
    url: jdbc:mariadb://localhost:3306/movie_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://172.20.35.147:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*" # Phải có dòng này thì Dashboard mới đọc được dữ liệu
  endpoint:
    health:
      show-details: always