server:
  port: 8888

spring:
  main:
    web-application-type: reactive

  application:
    name: api-gateway

  boot:
    admin:
      context-path: /dashboard

  cloud:
    gateway:
      server:
        webflux:
          # --- CẤU HÌNH ROUTES NGANG HÀNG VỚI GLOBALCORS ---
          routes:
            # 1. Route cho Movie Service
            - id: movie-service
              uri: lb://MOVIE-SERVICE
              predicates:
                - Path=/api/movies/**

            # 2. Route cho User Service
            - id: user-service
              uri: lb://USER-SERVICE
              predicates:
                - Path=/api/users/**, /register, /login

            # 3. Route cho Booking Service
            - id: booking-service
              uri: lb://BOOKING-SERVICE
              predicates:
                - Path=/api/bookings/**

            # 4. Route cho Payment Service
            - id: payment-service
              uri: lb://PAYMENT-SERVICE
              predicates:
                - Path=/api/payments/**

          #      # --- CẤU HÌNH CORS CHO FRONTEND ---
          global-cors:
            cors-configurations:
                '[/**]':
                    allowedOriginPatterns: "*"
                    allowedMethods:
                    - GET
                    - POST
                    - PUT
                    - DELETE
                    - OPTIONS
                    allowedHeaders: "*"
                    allowCredentials: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://172.20.35.147:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*" # Mở tất cả các cổng giám sát (health, info, metrics, gateway...)
  endpoint:
    health:
      show-details: always