server:
  port: 8888

spring:
  main:
    web-application-type: reactive

  application:
    name: api-gateway

  boot:
    admin:
      context-path: /dashboard

  cloud:
    gateway:
      server:
        webflux:
          routes:
            # Route số 1: Orchestrator Service (Luồng đặt tour trung tâm)
            - id: orchestrator-service
              uri: lb://ORCHESTRATOR-SERVICE
              predicates:
                - Path=/api/book-tour/**

            # Route số 2: User Service (Cho Frontend gọi Login)
            - id: user-service
              uri: lb://USER-SERVICE
              predicates:
                - Path=/login, /api/users/**

            # Route số 3: Tour Service (Cho Frontend gọi xem danh sách)
            - id: tour-service
              uri: lb://TOUR-SERVICE
              predicates:
                - Path=/api/tours/**

            - id: payment-service
              uri: lb://PAYMENT-SERVICE
              predicates:
                - Path=/api/payments/**

            - id: booking-service
              uri: lb://BOOKING-SERVICE
              predicates:
                - Path=/api/bookings/**

          # --- CẤU HÌNH CORS CHO FRONTEND ---
          global-cors:
            cors-configurations:
                '[/**]':
                    allowedOriginPatterns: "*"
                    allowedMethods:
                    - GET
                    - POST
                    - PUT
                    - DELETE
                    - OPTIONS
                    allowedHeaders: "*"
                    allowCredentials: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://172.16.33.175:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*" # Mở tất cả các cổng giám sát (health, info, metrics, gateway...)
  endpoint:
    health:
      show-details: always